# site settings
title: My Portfolio
subtitle: Nikhil Sunka
email: nikhilsunka69@gmail.com
description: Midterm Project
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 237 MacClelland Avenue
city: Glassboro
state: New Jersey
zip_code: 08028
country: United States of America
phone: +1 8565428655

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: 
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: 
  Twitter: 
  Facebook:
  Slack:

# build settings
markdown: kramdown

repository: compiler/compiler.github.io

sass:
  style: compressed
github: [metadata]
exclude: [vendor]
exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
- vendor
